### PR TITLE
Generate mirror list from data/mirrors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Anyon3** [comment]
thanks will test it and merge it asap

**Comment by noptrix** [comment]
btw, needs to be synced with current git version. there conflics with merging in

**Comment by Anyon3** [comment]
I tested your script, it appear that the generate-site.sh will not finish and stay stuck, but all the mirrors are correctly generated. I could debug it if you haven't time.

Another thing to fix is the protocol type, can you add https for https mirror and http for http mirror ? For now the protocol http is displayed even the mirror is https

Thanks your time btw

**Comment by ghost** [comment]
I'll fix that. I'll check if there is an EOF problem if it's just hanging.

**Pull request closed without merging**
