### PR TITLE
strap.sh - remove backup file pacman.confe

### LINKED ISSUE #1126: strap.sh creates "pacman.confe" without any notification
If you install BlackArch with strap.sh, you end up having "pacman.confe" besides usual "pacman.conf". The file is created with "update_pacman_conf()" procedure by sed utility:
```
# delete blackarch related entries if existing
sed -ie '/blackarch/{N;d}' /etc/pacman.conf
```

Shouldn't we have a note about it in terminal or in instructions on how to install?

### PR DESCRIPTION
**Pull request by heichblatt**
Hello,

this fixes BlackArch/blackarch#1126.

Cheers.

### CODE REVIEW

**Comment by hexcat** [comment]
Well, it won't create "pacman.confe" now, but my point wasn't the fact that file was created (which is good as backup) but the fact that it was created _silently_. I remember myself wondering where did I get the file a month after installation.

**Comment by hexcat** [comment]
Well, it won't create file now, but my point was to add a note, not removing the backup entirely.

**Comment by heichblatt** [comment]
I don't see the point of that backup file.

Proof this PR works:

```
$ docker run -ti heichblatt/archlinux-yaourt bash
$ curl https://raw.githubusercontent.com/heichblatt/blackarch-site/master/strap.sh | bash
(snip)
```

The extra file is gone, but the script still works:

```
$ stat /etc/pacman.confe
stat: cannot stat '/etc/pacman.confe': No such file or directory
$ yaourt -Ss blackarch | grep -v "^   " | wc -l
1532
```

**Comment by hexcat** [comment]
I guess you're right. The changes are minimal, so there shouldn't be cases in which it's needed

**Comment by heichblatt** [comment]
Hi all,

I updated the sha1 on the download page as well.
Please merge.

Cheers.

**Comment by noptrix** [comment]
Thanks a lot @heichblatt. We cannot merge it in yet, though: The sha1 sum is hardcoded in the blackarch-installer v0.2 (in the ISO as well), thus the installer would fail. I will merge it when we create the new ISOs. We can create a bugfix release of the ISOs soon. Need to talk to Pi3rrot (IRC).

**Comment by noptrix** [comment]
I will keep the PR open here. Again, thanks a lot.

**Comment by heichblatt** [comment]
All right, thanks.
Would you be interested in a patch switching to sha256?

**Pull request merged**
