### PR TITLE
Fixing gpg signature erorr

### PR DESCRIPTION
**Pull request by Seven7Up**
I updated pgp public key source link protocol prefix and port after failed (pacman) blackarch repository installation on Arch Linux.

### CODE REVIEW

**Comment by ikstream** [comment]
This failed on some occasions for me and others as well, so I would rather not merge it, esp. not as first option.

**Comment by Seven-7Up** [comment]
No problem, we research all time for the most useful option. YOU ARE
WELCOME!

**Comment by Seven7Up** [comment]
No problem, I am trying my best to improve our projects.
I am proud for being here.

**Comment by ikstream** [comment]
I was thinking about adding it as a third option. There haven't been any reported issues with the key fetching lately. Do you still encounter these regularly?

**Comment by Seven7Up** [comment]
Done!
In answer to your question, I haven't encountered any issue after using strap.sh with this fix. Not sure if this will be the same with others but I hope so.

**Comment by ikstream** [comment]
As we haven't had any issues reported besides of your, please add the hkp:80 as last fallback.

**Comment by Seven7Up** [comment]
Sorry for my delay, I made the `hkp:80` as 3th option.

**Review by ikstream — APPROVED** [review]

**Comment by ikstream** [comment]
Thank you for your contribution

**Comment by Seven7Up** [comment]
Hahah, please don't blame my old bad language, I am a none English speaking boy and I was only 15.

**Pull request merged**
